root = "."
tmp_dir = "tmp"

[build]
    bin = "main"
    cmd = "go build -o {{.Output}} {{.Input}}"
    exclude_dir = ["tmp", "client", "node_modules", "vendor"]
    include_ext = ["go"]
    exclude_file = []
    exclude_regex = ["_test.go"]
    exclude_unchanged = true
    follow_symlink = true
    kill_delay = "0s"
    log = "build-errors.log"
    send_interrupt = false
    stop_on_error = true

[color]
    app = ""
    build = "yellow"
    main = "magenta"
    runner = "green"
    watcher = "cyan"

[log]
    time = false

[misc]
    clean_on_exit = false